user1 = User.create(name: "sillhouette", password: "m")
user2 = User.create(name: "iamcatdad", password: "catz4lyf3")

user1.magic_cards.create(name: "Abrade", color: "Red", manna_cost: "1R",types: "Instant", rarity: "Uncommon", set: "Hour of Devastation", value:3, quantity:3)
user1.magic_cards.create(name: "Abrade (Full Art Promo)", color: "Red", manna_cost: "1R",types: "Instant", rarity: "Uncommon", set: "Hour of Devastation", value:1, quantity:3)
user1.magic_cards.create(name: "Abrupt Decay", color: "Multicolor", manna_cost: "BG",types: "Instant", rarity: "Rare", set: "Return To Ravnica", value:25, quantity:19)
user1.magic_cards.create(name: "Absolute Law", color: "White", manna_cost: "1W",types: "Enchantment", rarity: "Uncommon", set: "Urza's Saga", value:2, quantity:2)
user1.magic_cards.create(name: "Absorb", color: "Multicolor", manna_cost: "WUU",types: "Instant", rarity: "Rare", set: "invasion", value:5, quantity:2)
user1.magic_cards.create(name: "Abyssal Horror", color: "Black", manna_cost: "4BB",types: "Creature", rarity: "Rare", set: "Urza's Saga", value:2, quantity:1)
user1.magic_cards.create(name: "Abzan Charm", color: "Multicolor", manna_cost: "WBG",types: "Instant", rarity: "Uncommon", set: "Khans of Tarkir", value:2, quantity:1)
user1.magic_cards.create(name: "Academy Rector", color: "White", manna_cost: "3W",types: "Creature", rarity: "Rare", set: "Urza's Destiny", value:50, quantity:4)
user1.magic_cards.create(name: "Academy Ruins", color: "Land", manna_cost: "Land",types: "Land", rarity: "Rare", set: "Time Spiral", value:25, quantity:1)
user1.magic_cards.create(name: "Acidic Slime", color: "Green", manna_cost: "3GG",types: "Creature", rarity: "Uncommon", set: "Magic 2010", value:2, quantity:1)
user1.magic_cards.create(name: "Acorn Harvest", color: "Green", manna_cost: "3G",types: "Sorcery", rarity: "Common", set: "Torment", value:1, quantity:2)
user1.magic_cards.create(name: "Active Volcano", color: "Red", manna_cost: "R",types: "Instant", rarity: "Common", set: "Legends", value:1, quantity:1)
user1.magic_cards.create(name: "Ad Nauseam", color: "Black", manna_cost: "3BB",types: "Instant", rarity: "Rare", set: "Shards of Alara", value:10, quantity:1)
user1.magic_cards.create(name: "Adaptive Automaton", color: "Colorless", manna_cost: "3",types: "Artifact Creature", rarity: "Rare", set: "Magic 2012", value:7, quantity:1)
user1.magic_cards.create(name: "Advent of the Wurm", color: "Multicolor", manna_cost: "1GGW",types: "Instant", rarity: "Rare", set: "Dragon's Maze", value:3, quantity:1)
user1.magic_cards.create(name: "Aegis Angel", color: "White", manna_cost: "4WW",types: "Creature", rarity: "Rare", set: "Magic 2012", value:2, quantity:2)
user1.magic_cards.create(name: "Aegis of honor", color: "", manna_cost: "",types: "", rarity: "Rare", set: "Odyssey", value:1, quantity:1)
user1.magic_cards.create(name: "Aegis of the Gods", color: "White", manna_cost: "1W",types: "Enchantment Creature", rarity: "Rare", set: "Journey into Nyx", value:4, quantity:7)
user1.magic_cards.create(name: "Aether Vial", color: "Colorless", manna_cost: "1",types: "Artifact", rarity: "Uncommon", set: "Darksteel", value:200, quantity:8)
user1.magic_cards.create(name: "Aether Vial ", color: "Colorless", manna_cost: "1",types: "Artifact", rarity: "Rare", set: "Modern Masters", value:55, quantity:4)
user1.magic_cards.create(name: "Aetherflux Reservoir", color: "Colorless", manna_cost: "4",types: "Artifact", rarity: "Rare", set: "Kaladesh", value:4, quantity:2)
user1.magic_cards.create(name: "Aetherize", color: "Blue", manna_cost: "3U",types: "Instant", rarity: "Uncommon", set: "Gatecrash", value:1, quantity:1)
user1.magic_cards.create(name: "Aetherling", color: "Blue", manna_cost: "4UU",types: "Creature", rarity: "Rare", set: "Dragon's Maze", value:2, quantity:1)
user1.magic_cards.create(name: "Aetherspouts", color: "Blue", manna_cost: "3UU",types: "Instant", rarity: "Rare", set: "Magic 2015", value:2, quantity:2)
user1.magic_cards.create(name: "Ageless sentinels", color: "", manna_cost: "",types: "", rarity: "rare", set: "Scourge", value:1, quantity:1)
user1.magic_cards.create(name: "Agent of the Fates", color: "Black", manna_cost: "1BB",types: "Creature", rarity: "Rare", set: "Theros", value:2, quantity:2)
user1.magic_cards.create(name: "Aggressive Mining", color: "Red", manna_cost: "3R",types: "Enchantment", rarity: "Rare", set: "Magic 2015", value:1, quantity:2)
user1.magic_cards.create(name: "Ajani Caller of the Pride", color: "White", manna_cost: "1WW",types: "Planeswalker", rarity: "Mythic Rare", set: "Magic 2014", value:10, quantity:2)
user1.magic_cards.create(name: "Ajani Goldmane", color: "White", manna_cost: "2WW",types: "Planeswalker", rarity: "Rare", set: "Lorwyn", value:13, quantity:2)
user1.magic_cards.create(name: "Ajani mentor of Heroes", color: "Multicolor", manna_cost: "3GW",types: "Planeswalker", rarity: "Mythic Rare", set: "Journey Into Nyx", value:20, quantity:3)
user1.magic_cards.create(name: "Ajani Vengeant", color: "Multicolor", manna_cost: "2RW",types: "Planeswalker", rarity: "Mythic Rare", set: "Shards of Alara", value:15, quantity:1)
user1.magic_cards.create(name: "Akroan Horse", color: "Colorless", manna_cost: "4",types: "Artifact Creature", rarity: "Rare", set: "Theros", value:1, quantity:1)
user1.magic_cards.create(name: "Akroma Angel of Fury", color: "Red", manna_cost: "5RRR",types: "Legendary Creature", rarity: "Mythic Rare", set: "From the Vault: Angels", value:9, quantity:1)
user1.magic_cards.create(name: "Akroma angel of wrath", color: "", manna_cost: "",types: "", rarity: "Rare", set: "Legions", value:5, quantity:2)
user1.magic_cards.create(name: "Akroma's Blessing", color: "White", manna_cost: "2W",types: "Instant", rarity: "Uncommon", set: "Onslaught", value:2, quantity:1)
user1.magic_cards.create(name: "Akroma's Memorial", color: "Colorless", manna_cost: "7",types: "Legendary Artifact", rarity: "Mythic Rare", set: "Magic 2013", value:18, quantity:2)
user1.magic_cards.create(name: "Akroma's Vengeance", color: "White", manna_cost: "4WW",types: "Sorcery", rarity: "Rare", set: "Onslaught", value:2, quantity:1)
user1.magic_cards.create(name: "Alchemist's Refuge", color: "Land", manna_cost: "Land",types: "Land", rarity: "Rare", set: "Avacyn Restored", value:2, quantity:1)
user1.magic_cards.create(name: "Alexi Zephyr Mage", color: "Blue", manna_cost: "3UU",types: "Creature", rarity: "Rare", set: "Prophecy", value:2, quantity:1)
user1.magic_cards.create(name: "Alhammarret's Archive", color: "Colorless", manna_cost: "5",types: "Legendary Artifact", rarity: "Mythic Rare", set: "Magic Origins", value:8, quantity:2)
user1.magic_cards.create(name: "All Hallow's Eve", color: "Black", manna_cost: "2BB",types: "Sorcery", rarity: "Rare", set: "Legends", value:500, quantity:1)
user1.magic_cards.create(name: "All is Dust", color: "Colorless", manna_cost: "7",types: "Tribal Sorcery-Eldrazi", rarity: "Rare", set: "Modern Masters 2015", value:12, quantity:2)
user1.magic_cards.create(name: "All is Dust", color: "Colorless", manna_cost: "7",types: "Tribal Sorcery-Eldrazi", rarity: "Rare", set: "Rise of the Eldrazi", value:12, quantity:2)
user1.magic_cards.create(name: "All Sun's Dawn", color: "Green", manna_cost: "4G",types: "Sorcery", rarity: "Rare", set: "Modern Masters 2015", value:2, quantity:1)
user1.magic_cards.create(name: "Allhammarret's Archive", color: "Colorless", manna_cost: "5",types: "Legendary Artifact", rarity: "Mythic Rare", set: "Magic Origins", value:8, quantity:1)
user1.magic_cards.create(name: "Alms Beast", color: "Multicolor", manna_cost: "2WB",types: "Creature", rarity: "Rare", set: "Gatecrash", value:1, quantity:1)
user1.magic_cards.create(name: "Alpha Brawl", color: "Red", manna_cost: "6RR",types: "Sorcery", rarity: "Rare", set: "Dark Ascension", value:2, quantity:1)
user1.magic_cards.create(name: "Altar of Dementia", color: "Colorless", manna_cost: "2",types: "Artifact", rarity: "Rare", set: "Tempest", value:7, quantity:1)
user1.magic_cards.create(name: "Altered Ego", color: "Multicolor", manna_cost: "X2GU",types: "Creature", rarity: "Rare", set: "Shadows over Innistrad", value:2, quantity:1)
user1.magic_cards.create(name: "Aluren", color: "Green", manna_cost: "2GG",types: "Enchantment", rarity: "Rare", set: "Tempest", value:45, quantity:4)
user1.magic_cards.create(name: "Amber Prison", color: "Colorless", manna_cost: "4",types: "Artifact", rarity: "Rare", set: "Mirage", value:1, quantity:1)
user1.magic_cards.create(name: "Ambush Commander", color: "Green", manna_cost: "3GG",types: "Creature", rarity: "Rare", set: "Scourge", value:3, quantity:1)
user1.magic_cards.create(name: "Amnesia", color: "Blue", manna_cost: "3UUU",types: "Sorcery", rarity: "Uncommon", set: "The Dark", value:10, quantity:3)
user1.magic_cards.create(name: "Amugaba", color: "Blue", manna_cost: "5UU",types: "Creature", rarity: "Rare", set: "Odyssey", value:1, quantity:1)
user1.magic_cards.create(name: "Amulet of Vigor", color: "Colorless", manna_cost: "1",types: "Artifact", rarity: "Rare", set: "Worldwake", value:10, quantity:4)
user1.magic_cards.create(name: "Anafenza the Foremost", color: "Multicolor", manna_cost: "WBG",types: "Legendary Creature", rarity: "Mythic Rare", set: "Khans of Tarkir", value:2, quantity:1)
user1.magic_cards.create(name: "Anafenza, Kin-Tree Spirit", color: "White", manna_cost: "WW",types: "Legendary Creature", rarity: "Rare", set: "Dragons of Tarkir", value:7, quantity:3)
user1.magic_cards.create(name: "Ancestral Mask", color: "Green", manna_cost: "2G",types: "Enchantment-Aura", rarity: "Common", set: "Mercadian Masques", value:2, quantity:1)
user1.magic_cards.create(name: "Ancestral Recall", color: "Blue", manna_cost: "U",types: "Instant", rarity: "Rare", set: "EDH Casual Play", value:5, quantity:1)
user1.magic_cards.create(name: "Ancestral Recall", color: "Blue", manna_cost: "U",types: "Instant", rarity: "Rare", set: "Unlimited", value:20, quantity:1)
user1.magic_cards.create(name: "Ancestral Tribute", color: "White", manna_cost: "5WW",types: "Sorcery", rarity: "Rare", set: "Odyssey", value:1, quantity:3)
user1.magic_cards.create(name: "Ancestral Vision", color: "Blue", manna_cost: "U",types: "Sorcery", rarity: "Rare", set: "Time Spiral", value:66, quantity:6)
user1.magic_cards.create(name: "Ancient Craving", color: "Black", manna_cost: "3B",types: "Sorcery", rarity: "Rare", set: "Commander 2015", value:2, quantity:1)
user1.magic_cards.create(name: "Ancient Den", color: "Land", manna_cost: "Land",types: "Artifact Land", rarity: "Common", set: "Mirrodin", value:5, quantity:5)
user1.magic_cards.create(name: "Ancient Grudge", color: "Red", manna_cost: "1R",types: "Instant", rarity: "Common", set: "Innistrad", value:1, quantity:4)
user1.magic_cards.create(name: "Ancient Grudge", color: "Red", manna_cost: "1R",types: "Instant", rarity: "Common", set: "Time Spiral", value:1, quantity:1)
user1.magic_cards.create(name: "Ancient Hellkite", color: "Red", manna_cost: "4RRR",types: "Creature", rarity: "Rare", set: "Magic 2011", value:1, quantity:1)
user1.magic_cards.create(name: "Ancient Stirrings", color: "Green", manna_cost: "G",types: "Sorcery", rarity: "Common", set: "Rise of the Eldrazi", value:2, quantity:4)
user1.magic_cards.create(name: "Ancient Stirrings", color: "Green", manna_cost: "G",types: "Sorcery", rarity: "Uncommon", set: "Masters 25", value:2, quantity:1)
user1.magic_cards.create(name: "Ancient Tomb", color: "Land", manna_cost: "Land",types: "Land", rarity: "Uncommon", set: "Tempest", value:75, quantity:15)
user1.magic_cards.create(name: "Ancient Ziggurat", color: "Land", manna_cost: "Land",types: "Land", rarity: "Uncommon", set: "Premium Deck Series: Slivers", value:4, quantity:5)
user1.magic_cards.create(name: "Anciet Silverback", color: "", manna_cost: "",types: "", rarity: "Rare", set: "Urza's Destiny", value:1, quantity:1)
user1.magic_cards.create(name: "Angel of Deliverance", color: "White", manna_cost: "6WW",types: "Creature", rarity: "Rare", set: "Shadows over Innistrad", value:2, quantity:1)
user1.magic_cards.create(name: "Angel of Despair", color: "Multicolor", manna_cost: "3WWBB",types: "Creature", rarity: "Rare", set: "Guildpact", value:6, quantity:1)
user1.magic_cards.create(name: "Angel of Glory's Rise (1 foil)", color: "White", manna_cost: "5WW",types: "Creature", rarity: "Rare", set: "Avacyn Restored", value:2, quantity:2)
user1.magic_cards.create(name: "Angel of Jubilation", color: "White", manna_cost: "1WWW",types: "Creature", rarity: "Rare", set: "Avacyn Restored", value:6, quantity:1)
user1.magic_cards.create(name: "Angel of Retribution", color: "", manna_cost: "",types: "", rarity: "Rare", set: "Torment", value:1, quantity:1)
user1.magic_cards.create(name: "Angel of Sanctions", color: "White", manna_cost: "3WW",types: "Creature", rarity: "Mythic Rare", set: "Amonkhet", value:3, quantity:1)
user1.magic_cards.create(name: "Angel of Serenity", color: "White", manna_cost: "4WWW",types: "Creature", rarity: "Mythic Rare", set: "Return To Ravnica", value:7, quantity:1)
user1.magic_cards.create(name: "Angel of the Dire Hour", color: "White", manna_cost: "5WW",types: "Creature", rarity: "Rare", set: "Commander 2014", value:6, quantity:1)
user1.magic_cards.create(name: "Angelic Arbiter", color: "White", manna_cost: "5WW",types: "Creature", rarity: "Rare", set: "Magic 2011", value:2, quantity:1)
user1.magic_cards.create(name: "Angelic Captain", color: "Multicolor", manna_cost: "3RW",types: "Creature", rarity: "Rare", set: "Battle for Zendikar", value:2, quantity:1)
user1.magic_cards.create(name: "Angelic Chorus ", color: "", manna_cost: "",types: "", rarity: "Rare", set: "Urza's Saga", value:5, quantity:1)
user1.magic_cards.create(name: "Angelic Field Marshal", color: "White", manna_cost: "2WW",types: "Creature", rarity: "Rare", set: "Commander 2014", value:2, quantity:1)
user1.magic_cards.create(name: "Anger", color: "Red", manna_cost: "3R",types: "Creature", rarity: "Uncommon", set: "Judgement", value:2, quantity:4)
user1.magic_cards.create(name: "Anger of the Gods", color: "Red", manna_cost: "1RR",types: "Sorcery", rarity: "Rare", set: "Theros", value:6, quantity:4)
user1.magic_cards.create(name: "Anguished Unmaking", color: "Multicolor", manna_cost: "1WB",types: "Instant", rarity: "Rare", set: "Shadows over Innistrad", value:5, quantity:3)
user1.magic_cards.create(name: "Animate Dead", color: "Black", manna_cost: "1B",types: "Enchantment", rarity: "Uncommon", set: "Fifth Edition", value:3, quantity:1)
user1.magic_cards.create(name: "Animate Dead", color: "Black", manna_cost: "1B",types: "Enchantment-Aura", rarity: "Uncommon", set: "Revised Edition", value:2, quantity:3)
user1.magic_cards.create(name: "Animate Dead", color: "Black", manna_cost: "1B",types: "Enchant Dead Creature", rarity: "Uncommon", set: "Unlimited", value:25, quantity:4)
user1.magic_cards.create(name: "animate dead (1 foil)", color: "Black", manna_cost: "1B",types: "Enchantment-Aura", rarity: "Uncommon", set: "Eternal Masters", value:3, quantity:4)
user1.magic_cards.create(name: "Animate Wall", color: "White", manna_cost: "W",types: "Enchantment-Aura", rarity: "Rare", set: "Sixth Edition", value:1, quantity:1)
user1.magic_cards.create(name: "Animist's Awakening", color: "Green", manna_cost: "XG",types: "Sorcery", rarity: "Rare", set: "Magic Origins", value:4, quantity:3)
user1.magic_cards.create(name: "Ankh of Mishra", color: "Colorless", manna_cost: "2",types: "Artifact", rarity: "Uncommon", set: "Unlimited", value:20, quantity:1)
user1.magic_cards.create(name: "Ankle Shanker", color: "Multicolor", manna_cost: "2RWB",types: "Creature", rarity: "Rare", set: "Khans of Tarkir", value:1, quantity:1)
user1.magic_cards.create(name: "Anointed Procession", color: "White", manna_cost: "3W",types: "Enchantment", rarity: "Rare", set: "Amonkhet", value:2, quantity:1)
user1.magic_cards.create(name: "Ant Queen", color: "Green", manna_cost: "3GG",types: "Creature", rarity: "Rare", set: "Modern Masters 2015", value:2, quantity:1)
user1.magic_cards.create(name: "Anthousa setessan hero", color: "Green", manna_cost: "3GG",types: "Legendary Creature", rarity: "Rare", set: "Theros", value:1, quantity:1)
user1.magic_cards.create(name: "Apocalypse Hydra", color: "Multicolor", manna_cost: "XRG",types: "Creature", rarity: "Rare", set: "Modern Masters 2015", value:4, quantity:2)
user1.magic_cards.create(name: "Approach of the Second Sun", color: "White", manna_cost: "6W",types: "Sorcery", rarity: "Rare", set: "Amonkhet", value:3, quantity:2)
user1.magic_cards.create(name: "Arashin Foremost (1 foil)", color: "White", manna_cost: "1WW",types: "Creature", rarity: "Rare", set: "Dragons of Tarkir", value:2, quantity:2)
user1.magic_cards.create(name: "Arbor Colossus", color: "Green", manna_cost: "2GGG",types: "Creature", rarity: "Rare", set: "Theros", value:1, quantity:1)
user1.magic_cards.create(name: "Arc Trail", color: "Red", manna_cost: "1R",types: "Sorcery", rarity: "Uncommon", set: "Scars of Mirrodin", value:1, quantity:2)
user1.magic_cards.create(name: "Arcane Denial ", color: "Blue", manna_cost: "1U",types: "Instant", rarity: "Uncommon", set: "Alliances", value:2, quantity:1)
user1.magic_cards.create(name: "Arcane Lighthouse", color: "Land", manna_cost: "Land",types: "Land", rarity: "Uncommon", set: "Commander 2014", value:4, quantity:1)
user1.magic_cards.create(name: "Arcane Melee", color: "Blue", manna_cost: "4U",types: "Enchantment", rarity: "Rare", set: "Avacyn Restored", value:2, quantity:2)
user1.magic_cards.create(name: "Arcane Sanctum", color: "Land", manna_cost: "Land",types: "Land", rarity: "Uncommon", set: "Shards of Alara", value:4, quantity:3)
user1.magic_cards.create(name: "Arcanis the Omnipotent", color: "Blue", manna_cost: "3UUU",types: "Legendary Creature", rarity: "Rare", set: "Eternal Masters", value:3, quantity:1)
user1.magic_cards.create(name: "Arcbond", color: "Red", manna_cost: "2R",types: "Instant", rarity: "Rare", set: "Fate Reforged", value:1, quantity:1)
user1.magic_cards.create(name: "Arcbound Ravager (1 Foil)", color: "Colorless", manna_cost: "2",types: "Artifact Creature", rarity: "Rare", set: "Modern Masters", value:72, quantity:5)
user1.magic_cards.create(name: "Archangel Avacyn", color: "White", manna_cost: "3WW",types: "Legendary Creature", rarity: "Mythic Rare", set: "Shadows over Innistrad", value:50, quantity:5)
user1.magic_cards.create(name: "Archangel of Thune", color: "White", manna_cost: "3WW",types: "Creature", rarity: "Mythic Rare", set: "Magic 2014", value:40, quantity:2)
user1.magic_cards.create(name: "Archangel of Tithes", color: "White ", manna_cost: "1WWW",types: "Creature", rarity: "Mythic Rare", set: "Magic Origins", value:24, quantity:2)
user1.magic_cards.create(name: "Archetypes of Agression", color: "Red", manna_cost: "1RR",types: "Enchantment-Creature", rarity: "Uncommon", set: "Born of the Gods", value:2, quantity:3)
user1.magic_cards.create(name: "Archfiend of Depravity", color: "Black", manna_cost: "3BB",types: "Creature", rarity: "Rare", set: "Fate Reforged", value:2, quantity:1)
user1.magic_cards.create(name: "Archive Trap", color: "Blue", manna_cost: "3UU",types: "Instant", rarity: "Rare", set: "Zendikar", value:12, quantity:2)
user1.magic_cards.create(name: "Archivist", color: "Blue", manna_cost: "2UU",types: "Creature", rarity: "Rare", set: "Ninth Edition", value:1, quantity:1)
user1.magic_cards.create(name: "Archivist", color: "Blue", manna_cost: "2UU",types: "Creature", rarity: "Rare", set: "Urza's Legacy", value:1, quantity:1)
user1.magic_cards.create(name: "Archon of Justice", color: "White", manna_cost: "3WW",types: "Creature", rarity: "Rare", set: "Magic 2012", value:2, quantity:2)
user1.magic_cards.create(name: "Archon of Triumvirate", color: "Multicolor", manna_cost: "5WU",types: "Creature", rarity: "Rare", set: "Return To Ravnica", value:1, quantity:1)
user1.magic_cards.create(name: "Archwing Dragon", color: "red", manna_cost: "2RR",types: "Creature", rarity: "Rare", set: "Avacyn Restored", value:2, quantity:2)
user1.magic_cards.create(name: "Argent Sphinx", color: "Blue", manna_cost: "2UU",types: "Creature", rarity: "Rare", set: "Modern Masters 2015", value:2, quantity:1)
user1.magic_cards.create(name: "Argent Sphinx", color: "Blue", manna_cost: "2UU",types: "Creature", rarity: "Rare", set: "Scars of Mirrodin", value:1, quantity:1)
user1.magic_cards.create(name: "Argentum Armor", color: "Colorless", manna_cost: "6",types: "Artifact-Equipment", rarity: "Rare", set: "Commander 2014", value:3, quantity:5)
user1.magic_cards.create(name: "Argothian Enchantress", color: "Green", manna_cost: "1G",types: "Creature", rarity: "Mythic Rare", set: "Eternal Masters", value:12, quantity:4)
user1.magic_cards.create(name: "Arid Mesa", color: "Land", manna_cost: "Land",types: "Land", rarity: "Rare", set: "Zendikar", value:80, quantity:7)
user1.magic_cards.create(name: "Arlinn Kord/ Arlinn Embraced by the Moon", color: "Multicolor", manna_cost: "2RG",types: "Planeswalker", rarity: "Mythic Rare", set: "Shadows over Innistrad", value:50, quantity:3)
user1.magic_cards.create(name: "Armageddon", color: "White", manna_cost: "3W",types: "Sorcery", rarity: "Rare", set: "Anthologies", value:4, quantity:2)
user1.magic_cards.create(name: "Armageddon", color: "White", manna_cost: "3W",types: "Sorcery", rarity: "Uncommon", set: "Revised Edition", value:6, quantity:2)
user1.magic_cards.create(name: "Armory Automoton", color: "Colorless", manna_cost: "3",types: "Artifact Creature", rarity: "Rare", set: "Commander 2016", value:4, quantity:1)
user1.magic_cards.create(name: "Arrogant Wurm", color: "Green", manna_cost: "3GG",types: "Creature", rarity: "Uncommon", set: "Torment", value:1, quantity:2)
user1.magic_cards.create(name: "Artificial Evolution", color: "Blue", manna_cost: "U",types: "Instant", rarity: "Rare", set: "Onslaught", value:1, quantity:1)
user1.magic_cards.create(name: "Artisan of Forms", color: "Blue", manna_cost: "1U",types: "Creature", rarity: "Rare", set: "Theros", value:1, quantity:1)
user1.magic_cards.create(name: "As Foretold", color: "Blue", manna_cost: "2U",types: "Enchantment", rarity: "Rare", set: "Amonkhet", value:4, quantity:2)
user1.magic_cards.create(name: "Asceticism", color: "Green", manna_cost: "3GG",types: "Enchantment", rarity: "Rare", set: "Scars of Mirrodin", value:13, quantity:3)
user1.magic_cards.create(name: "Ashcloud Phoenix (1 foil)", color: "Red", manna_cost: "2RR",types: "Creature", rarity: "Mythic Rare", set: "Khans of Tarkir", value:4, quantity:1)
user1.magic_cards.create(name: "Ashen Powder", color: "Black", manna_cost: "2BB",types: "Sorcery", rarity: "Rare", set: "Sixth Edition", value:2, quantity:1)
user1.magic_cards.create(name: "Ashen Rider", color: "Multicolor", manna_cost: "4WWBB",types: "Creature", rarity: "Mythic Rare", set: "Theros", value:4, quantity:3)
user1.magic_cards.create(name: "Ashiok, Nightmare Weaver", color: "Multicolor", manna_cost: "1UB",types: "Planeswalker", rarity: "Mythic Rare", set: "Theros", value:8, quantity:4)
user1.magic_cards.create(name: "ashnod's alter", color: "Colorless", manna_cost: "3",types: "Artifact", rarity: "Uncommon", set: "Eternal Masters", value:3, quantity:2)
user1.magic_cards.create(name: "Assault formation", color: "Green", manna_cost: "1G",types: "Enchantment", rarity: "Rare", set: "Dragons of Tarkir", value:6, quantity:1)
user1.magic_cards.create(name: "Assault Strobe", color: "Red", manna_cost: "R",types: "Sorcery", rarity: "Common", set: "Scars of Mirrodin", value:2, quantity:4)
user1.magic_cards.create(name: "Assembled Alphas", color: "Red", manna_cost: "5R",types: "Creature", rarity: "Rare", set: "Eldritch Moon", value:1, quantity:1)
user1.magic_cards.create(name: "Asylum Visitor", color: "Black", manna_cost: "1B",types: "Creature", rarity: "Rare", set: "Shadows over Innistrad", value:3, quantity:1)
user1.magic_cards.create(name: "Atarka world render", color: "Multicolor", manna_cost: "5RG",types: "Legendary Creature", rarity: "Rare", set: "Fate Reforged", value:2, quantity:1)
user1.magic_cards.create(name: "Atarka's Command", color: "Multicolor", manna_cost: "RG",types: "Instant", rarity: "Rare", set: "Dragons of Tarkir", value:37, quantity:4)
user1.magic_cards.create(name: "Athreos God of Passage", color: "Multicolor", manna_cost: "1WB",types: "Legendary Enchantment Creature-God", rarity: "Mythic Rare", set: "Journey into Nyx", value:16, quantity:1)
user1.magic_cards.create(name: "Atog", color: "Red", manna_cost: "1R",types: "Creature", rarity: "Common", set: "Revised Edition", value:1, quantity:4)
user1.magic_cards.create(name: "Attrition ", color: "Black", manna_cost: "1BB",types: "Enchantment", rarity: "Rare", set: "Urza's Destiny", value:14, quantity:1)
user1.magic_cards.create(name: "Aura of Silence", color: "White", manna_cost: "1WW",types: "Enchantment", rarity: "Uncommon", set: "Tenth Edition", value:3, quantity:1)
user1.magic_cards.create(name: "Aura of Silence", color: "White", manna_cost: "1WW",types: "Enchantment", rarity: "Uncommon", set: "Weatherlight", value:3, quantity:1)
user1.magic_cards.create(name: "Aura Shards", color: "Multicolor", manna_cost: "1GW",types: "Enchantment", rarity: "Uncommon", set: "Invasion", value:8, quantity:1)
user1.magic_cards.create(name: "Aurelia the warleader", color: "Multicolor", manna_cost: "2RRWW",types: "Legendary Creature", rarity: "Mythic Rare", set: "Gatecrash", value:7, quantity:1)
user1.magic_cards.create(name: "Auriok Champion", color: "White", manna_cost: "WW",types: "Creature", rarity: "Rare", set: "Fifth Dawn", value:2, quantity:2)
user1.magic_cards.create(name: "Auriok Salvagers", color: "White", manna_cost: "3W",types: "Creature", rarity: "Rare", set: "Modern Masters", value:1, quantity:1)
user1.magic_cards.create(name: "Auriok Steel Shaper", color: "", manna_cost: "",types: "", rarity: "Rare", set: "Mirrodin", value:1, quantity:2)
user1.magic_cards.create(name: "Auriok Windwalker", color: "White", manna_cost: "3W",types: "Creature", rarity: "Rare", set: "Fifth Dawn", value:2, quantity:1)
user1.magic_cards.create(name: "Austere Command", color: "White", manna_cost: "4WW",types: "Sorcery", rarity: "Rare", set: "Lorwyn", value:14, quantity:1)
user1.magic_cards.create(name: "Authority of the Consuls", color: "White", manna_cost: "W",types: "Enchantment", rarity: "Rare", set: "Kaladesh", value:4, quantity:2)
user1.magic_cards.create(name: "Avacyn Guardian Angel", color: "White", manna_cost: "2WWW",types: "Legendary Creature", rarity: "Rare", set: "Magic 2015", value:2, quantity:2)
user1.magic_cards.create(name: "Avacyn, Angel of Hope", color: "White", manna_cost: "5WWW",types: "Legendary Creature", rarity: "Mythic Rare", set: "Avacyn Restored", value:35, quantity:3)
user1.magic_cards.create(name: "Avacyn's Judgement", color: "Red", manna_cost: "1R",types: "Sorcery", rarity: "Rare", set: "Shadows over Innistrad", value:3, quantity:1)
user1.magic_cards.create(name: "Avalanche Riders", color: "Red", manna_cost: "3R",types: "Creature", rarity: "Uncommon", set: "Urza's Legacy", value:2, quantity:1)
user1.magic_cards.create(name: "Avalanche Tusker", color: "Multicolor", manna_cost: "2GBR",types: "Creature", rarity: "Rare", set: "Khans of Tarkir", value:1, quantity:1)
user1.magic_cards.create(name: "Avarice Amulet", color: "Colorless", manna_cost: "4",types: "Artifact-Equipment", rarity: "Rare", set: "Magic 2015", value:2, quantity:1)
user1.magic_cards.create(name: "Avaricious Dragon", color: "Red", manna_cost: "2RR",types: "Creature", rarity: "Mythic Rare", set: "Magic Origins", value:6, quantity:1)
user1.magic_cards.create(name: "Avatar of Fury", color: "Red", manna_cost: "6RR",types: "Creature", rarity: "Rare", set: "Prophecy", value:2, quantity:2)
user1.magic_cards.create(name: "Avatar of Hope", color: "White", manna_cost: "6WW",types: "Creature", rarity: "Rare", set: "Prophecy", value:2, quantity:2)
user1.magic_cards.create(name: "Avatar of Might", color: "Green", manna_cost: "6GG",types: "Creature", rarity: "Rare", set: "Prophecy", value:2, quantity:1)
user1.magic_cards.create(name: "Avatar of Will", color: "Blue", manna_cost: "6UU",types: "Creature", rarity: "Rare", set: "Prophecy", value:2, quantity:2)
user1.magic_cards.create(name: "Avatar of Woe", color: "Black", manna_cost: "6BB",types: "Creature", rarity: "Rare", set: "Prophecy", value:4, quantity:3)
user1.magic_cards.create(name: "Aven Brigadier", color: "White", manna_cost: "3WWW",types: "Creature", rarity: "Rare", set: "Onslaught", value:2, quantity:1)
user1.magic_cards.create(name: "Aven Mindcensor", color: "White", manna_cost: "2W",types: "Creature", rarity: "Uncommon", set: "Future Sight", value:15, quantity:3)
user1.magic_cards.create(name: "Aven Mindcensor", color: "White", manna_cost: "2W",types: "Creature", rarity: "Rare", set: "Amonkhet", value:4, quantity:1)
user1.magic_cards.create(name: "Aven Shrine", color: "White", manna_cost: "1WW",types: "Enchantment", rarity: "Rare", set: "Odyssey", value:1, quantity:1)
user1.magic_cards.create(name: "Avenger en dal", color: "White", manna_cost: "1W",types: "Creature", rarity: "Rare", set: "Nemesis", value:1, quantity:1)
user1.magic_cards.create(name: "Avoid Fate", color: "Green", manna_cost: "G",types: "Instant", rarity: "Rare", set: "Legends", value:5, quantity:4)
user1.magic_cards.create(name: "Avoid Fate", color: "Green", manna_cost: "G",types: "Instant", rarity: "Rare", set: "Time Spiral", value:2, quantity:3)
user1.magic_cards.create(name: "Ayli Eternal Pilgrim", color: "Multicolor", manna_cost: "WB",types: "Legendary Creature", rarity: "Rare", set: "Oath of the Gatewatch", value:6, quantity:1)
user1.magic_cards.create(name: "Azorious Guildmage", color: "Multicolor", manna_cost: "(W/B)(W/B)",types: "Creature", rarity: "Uncommon", set: "Dissension", value:2, quantity:3)
user1.magic_cards.create(name: "Azorius Signet", color: "Colorless", manna_cost: "2",types: "Artifact", rarity: "Common", set: "Dissension", value:1, quantity:1)
user1.magic_cards.create(name: "Azusa Lost but seeking", color: "Green", manna_cost: "2G",types: "Legendary Creature", rarity: "Rare", set: "Champions of Kamigawa", value:40, quantity:3)
user1.magic_cards.create(name: "Azusa Lost but Seeking", color: "Green", manna_cost: "2G",types: "Legendary Creature", rarity: "Rare", set: "Masters 25", value:15, quantity:1)
user1.magic_cards.create(name: "Back to Basics", color: "Blue", manna_cost: "2U",types: "Enchantment", rarity: "Rare", set: "Urza's Legacy", value:30, quantity:4)
user1.magic_cards.create(name: "Badlands", color: "Land", manna_cost: "Land",types: "Land", rarity: "Rare", set: "Revised Edition", value:160, quantity:6)
user1.magic_cards.create(name: "Balan Wandering Knight", color: "White", manna_cost: "2WW",types: "Legendary Creature", rarity: "Rare", set: "Commander 2017", value:3, quantity:1)
user1.magic_cards.create(name: "Balance ", color: "White", manna_cost: "1W",types: "Sorcery", rarity: "Rare", set: "Revised Edition", value:2, quantity:2)
user1.magic_cards.create(name: "Balefire Dragon", color: "Red", manna_cost: "5RR",types: "Creature", rarity: "Mythic Rare", set: "Innistrad", value:15, quantity:1)
user1.magic_cards.create(name: "Balefire Liege", color: "Multicolor", manna_cost: "2(R/W)(R/W)(R/W)",types: "Creature", rarity: "Rare", set: "Eventide", value:11, quantity:4)
user1.magic_cards.create(name: "Baleful Strix", color: "Multicolor", manna_cost: "UB",types: "Creature", rarity: "Rare", set: "Eternal Masters", value:12, quantity:2)
user1.magic_cards.create(name: "Baleful Strix", color: "Multicolor", manna_cost: "UB",types: "Creature", rarity: "Rare", set: "Planeschase 2012", value:12, quantity:7)
user1.magic_cards.create(name: "Baleful Strix", color: "Multicolor", manna_cost: "UB",types: "Creature", rarity: "Rare", set: "Commander 2013", value:5, quantity:1)
user1.magic_cards.create(name: "Ball Lightning", color: "Red", manna_cost: "RRR",types: "Creature", rarity: "Rare", set: "Magic 2010", value:5, quantity:4)
user1.magic_cards.create(name: "Balm of Restoration", color: "Colorless", manna_cost: "2",types: "Artifact", rarity: "Rare", set: "Fallen Empires", value:2, quantity:1)
user1.magic_cards.create(name: "Banefire", color: "Red", manna_cost: "XR",types: "Sorcery", rarity: "Rare", set: "Modern Masters 2015", value:2, quantity:1)
user1.magic_cards.create(name: "Baneslayer Angel", color: "White", manna_cost: "3WW",types: "Creature", rarity: "Mythic Rare", set: "Magic 2011", value:15, quantity:1)
user1.magic_cards.create(name: "Baral Chief of Compliance", color: "Blue", manna_cost: "1U",types: "Legendary Creature", rarity: "Rare", set: "Aether Revolt", value:5, quantity:3)
user1.magic_cards.create(name: "Barbarian Ring", color: "Land", manna_cost: "Land",types: "Land", rarity: "Uncommon", set: "Odyssey", value:1, quantity:1)
user1.magic_cards.create(name: "Barrage Tyrant", color: "Colorless", manna_cost: "4R",types: "Creature-Eldrazi", rarity: "Rare", set: "Battle for Zendikar", value:1, quantity:1)
user1.magic_cards.create(name: "Barren Moor", color: "Land", manna_cost: "Land",types: "Land", rarity: "Common", set: "Onslaught", value:1, quantity:4)
user1.magic_cards.create(name: "Barrin's Codex", color: "", manna_cost: "",types: "", rarity: "Rare", set: "Urza's saga", value:1, quantity:1)
user1.magic_cards.create(name: "Basking Rootwalla", color: "Green", manna_cost: "G",types: "Creature", rarity: "Common", set: "Torment", value:1, quantity:3)
user1.magic_cards.create(name: "Bastion Protector", color: "White", manna_cost: "2W",types: "Creature", rarity: "Rare", set: "Commander 2015", value:2, quantity:1)
user1.magic_cards.create(name: "Batterskull", color: "Colorless", manna_cost: "5",types: "Artifact-Equipment", rarity: "Mythic Rare", set: "New Phyrexia", value:21, quantity:6)
user1.magic_cards.create(name: "Battle of wits", color: "Blue", manna_cost: "3UU",types: "Enchantment", rarity: "Rare", set: "Magic 2013", value:1, quantity:2)
user1.magic_cards.create(name: "Battle Screech", color: "White", manna_cost: "2WW",types: "Sorcery", rarity: "Uncommon ", set: "Judgement", value:6, quantity:4)
user1.magic_cards.create(name: "Battlefield Forge", color: "Land", manna_cost: "Land",types: "Land", rarity: "Rare", set: "Magic 2015", value:8, quantity:1)
user1.magic_cards.create(name: "Battlefield Forge", color: "Land", manna_cost: "Land",types: "Land", rarity: "Rare", set: "Magic Origins", value:3, quantity:1)
user1.magic_cards.create(name: "Battlefield Thaumaturge", color: "Blue", manna_cost: "1U",types: "Creature", rarity: "Rare", set: "Journey into Nyx", value:2, quantity:1)
user1.magic_cards.create(name: "Battlegrace Angel", color: "White", manna_cost: "3WW",types: "Creature", rarity: "Rare", set: "Modern Masters 2015", value:3, quantity:1)
user1.magic_cards.create(name: "Bayou", color: "Land", manna_cost: "Land",types: "Land", rarity: "Rare", set: "Unlimited", value:500, quantity:1)
user1.magic_cards.create(name: "Bayou", color: "Land", manna_cost: "Land",types: "Land", rarity: "Rare", set: "Revised Edition", value:280, quantity:8)
user1.magic_cards.create(name: "Bazaar of Baghdad", color: "Land", manna_cost: "Land",types: "Land", rarity: "Rare", set: "Arabian Nights", value:1600, quantity:1)
user1.magic_cards.create(name: "Beacon of Destiny", color: "White", manna_cost: "1W",types: "Creature", rarity: "Rare", set: "Legions", value:1, quantity:1)
user1.magic_cards.create(name: "Beacon of Immortality", color: "White", manna_cost: "5W",types: "Instant", rarity: "Rare", set: "Fifth Dawn", value:10, quantity:1)
user1.magic_cards.create(name: "Bear Umbra", color: "Green", manna_cost: "2GG",types: "Enchantment-Aura", rarity: "Rare", set: "Rise of the Eldrazi", value:6, quantity:1)
user1.magic_cards.create(name: "Bearer of Silence", color: "Colorless", manna_cost: "1B",types: "Creature-Eldrazi", rarity: "Rare", set: "Oath of the Gatewatch", value:3, quantity:1)
user1.magic_cards.create(name: "Bearer of the Heavens", color: "Red", manna_cost: "7R",types: "Creature", rarity: "Rare", set: "Journey into Nyx", value:2, quantity:2)
user1.magic_cards.create(name: "Beast Within", color: "Green", manna_cost: "2G",types: "Instant", rarity: "Uncommon", set: "New Phyrexia", value:8, quantity:1)
user1.magic_cards.create(name: "Beastcaller Savant", color: "Green", manna_cost: "1G",types: "Creature", rarity: "Rare", set: "Battle for Zendikar", value:3, quantity:1)
user1.magic_cards.create(name: "Beastmaster Ascension", color: "Green", manna_cost: "2G",types: "Enchantment", rarity: "Rare", set: "Commander 2015", value:2, quantity:4)
user1.magic_cards.create(name: "Beck/ Call", color: "Multicolor", manna_cost: "GU/ 4WU",types: "Sorcery", rarity: "Rare", set: "Dragon's Maze", value:3, quantity:1)
user1.magic_cards.create(name: "Become Immense", color: "Green", manna_cost: "5G",types: "Instant", rarity: "Uncommon", set: "Khans of Tarkir", value:2, quantity:2)
user1.magic_cards.create(name: "Bedlam Reveler", color: "Red", manna_cost: "6RR",types: "Creature", rarity: "Rare", set: "Eldritch Moon", value:3, quantity:2)
user1.magic_cards.create(name: "Beguiler of Wills", color: "Blue", manna_cost: "3UU",types: "Creature", rarity: "Mythic Rare", set: "Dark Ascension", value:2, quantity:3)
user1.magic_cards.create(name: "Behold the Beyond", color: "Black", manna_cost: "5BB",types: "Sorcery", rarity: "Mythic Rare", set: "Shadows over Innistrad", value:3, quantity:1)
user1.magic_cards.create(name: "Belbe's Portal", color: "Colorless", manna_cost: "5",types: "Artifact", rarity: "Rare", set: "Nemesis", value:5, quantity:1)
user1.magic_cards.create(name: "Belligerent Sliver", color: "Red", manna_cost: "2R",types: "Creature", rarity: "Uncommon", set: "Magic 2015", value:1, quantity:1)
user1.magic_cards.create(name: "Benalish Hero", color: "White", manna_cost: "W",types: "Creature", rarity: "Common", set: "Unlimited", value:1, quantity:2)
user1.magic_cards.create(name: "Berserk", color: "Green", manna_cost: "G",types: "Instant", rarity: "Rare", set: "Conspiracy: Take the Crown", value:52, quantity:4)
user1.magic_cards.create(name: "Berserker's Onslaught", color: "Red", manna_cost: "3RR",types: "Enchantment", rarity: "Rare", set: "Dragons of Tarkir", value:2, quantity:1)
user1.magic_cards.create(name: "Bident of Thassa", color: "Blue", manna_cost: "2UU",types: "Legendary Enchantment Artifact", rarity: "Rare", set: "Masters 25", value:3, quantity:1)
user1.magic_cards.create(name: "Bind", color: "Green", manna_cost: "1G",types: "Instant", rarity: "Rare", set: "Invasion", value:2, quantity:4)
user1.magic_cards.create(name: "Biovisionary", color: "Multicolor", manna_cost: "1GU",types: "Creature", rarity: "Rare", set: "Gatecrash", value:2, quantity:1)
user1.magic_cards.create(name: "Birchlore Rangers", color: "Green", manna_cost: "G",types: "Creature", rarity: "Common", set: "Onslaught", value:1, quantity:2)
user1.magic_cards.create(name: "Birds of Paradise", color: "Green", manna_cost: "G",types: "Creature", rarity: "Rare", set: "Magic 2012", value:12, quantity:3)
user1.magic_cards.create(name: "Birthing Pod", color: "Colorless", manna_cost: "3(G or 2 Life)",types: "Artifact", rarity: "Rare", set: "New Phyrexia", value:20, quantity:5)
user1.magic_cards.create(name: "Bitterblossom", color: "Black", manna_cost: "1B",types: "Enchantment", rarity: "Rare", set: "Morningtide", value:40, quantity:2)
user1.magic_cards.create(name: "Black Knight", color: "Black", manna_cost: "BB",types: "Creature", rarity: "Uncommon", set: "Revised Edition", value:1, quantity:4)
user1.magic_cards.create(name: "Black Lotus", color: "Colorless", manna_cost: "0",types: "Artifact", rarity: "Rare", set: "EDH Casual Play", value:5, quantity:1)
user1.magic_cards.create(name: "Black Lotus", color: "Colorless", manna_cost: "0",types: "Artifact", rarity: "Rare", set: "Unlimited", value:20, quantity:1)
user1.magic_cards.create(name: "Black Mana Battery", color: "Colorless", manna_cost: "4",types: "Artifact", rarity: "Rare", set: "Fourth Edition", value:1, quantity:1)
user1.magic_cards.create(name: "Black Vise", color: "Colorless", manna_cost: "1",types: "Artifact", rarity: "Common", set: "Revised Edition", value:2, quantity:3)
user1.magic_cards.create(name: "Black Vise", color: "Colorless", manna_cost: "1",types: "Artifact", rarity: "Common", set: "Unlimited", value:20, quantity:1)
user1.magic_cards.create(name: "Blackcleave Cliffs", color: "Land", manna_cost: "Land",types: "Land", rarity: "Rare", set: "Scars of Mirrodin", value:40, quantity:4)
user1.magic_cards.create(name: "Blade of Selves", color: "Colorless", manna_cost: "2",types: "Artifact-Equipment", rarity: "Rare", set: "Commander 2015", value:10, quantity:1)
user1.magic_cards.create(name: "Blade Sliver", color: "Red", manna_cost: "2R",types: "Creature", rarity: "Uncommon", set: "Legions", value:2, quantity:1)
user1.magic_cards.create(name: "bladewing the risen", color: "Multicolor", manna_cost: "3BBRR",types: "", rarity: "Rare", set: "Scourge", value:2, quantity:1)
user1.magic_cards.create(name: "Blanket of Night", color: "Black", manna_cost: "1BB",types: "Enchantment", rarity: "Uncommon", set: "Visions", value:2, quantity:4)
user1.magic_cards.create(name: "Blasphemous Act", color: "Red", manna_cost: "8R",types: "Sorcery", rarity: "rare", set: "Innistrad", value:2, quantity:1)
user1.magic_cards.create(name: "Blazing Archon", color: "White", manna_cost: "6WWW",types: "Creature", rarity: "Rare", set: "Ravnica", value:5, quantity:1)
user1.magic_cards.create(name: "Blazing Shoal", color: "Red", manna_cost: "XRR",types: "Instant", rarity: "Rare", set: "Betrayers of Kamigawa", value:3, quantity:4)
user1.magic_cards.create(name: "Blessed Alliance", color: "White", manna_cost: "1W",types: "Instant", rarity: "Uncommon", set: "Eldritch Moon", value:3, quantity:2)
user1.magic_cards.create(name: "Blessed Reincarnation", color: "Blue", manna_cost: "3U",types: "Instant", rarity: "Rare", set: "Dragons of Tarkir", value:2, quantity:1)
user1.magic_cards.create(name: "Blight Herder", color: "Colorless", manna_cost: "5",types: "Creature-Eldrazi", rarity: "Rare", set: "Battle for Zendikar", value:2, quantity:1)
user1.magic_cards.create(name: "Blight Mamba", color: "Green", manna_cost: "1G",types: "Creature", rarity: "Common", set: "Scars of Mirrodin", value:2, quantity:5)
user1.magic_cards.create(name: "Blighted Agent ", color: "Blue", manna_cost: "1U",types: "Creature", rarity: "Common", set: "New Phyrexia", value:2, quantity:4)
user1.magic_cards.create(name: "Blightsteel Colossus", color: "Colorless", manna_cost: "12",types: "Artifact Creature", rarity: "Mythic Rare", set: "Mirrodin Besiged", value:30, quantity:3)
user1.magic_cards.create(name: "Blind Obediance", color: "White", manna_cost: "1W",types: "Enchantment", rarity: "Rare", set: "Gatecrash", value:3, quantity:4)
user1.magic_cards.create(name: "Blinding Angel", color: "", manna_cost: "",types: "", rarity: "Rare", set: "Nemesis", value:2, quantity:1)
user1.magic_cards.create(name: "Blinkmoth Nexus", color: "Land", manna_cost: "Land",types: "Land", rarity: "Rare", set: "Modern Masters 2015", value:13, quantity:0)
user1.magic_cards.create(name: "Blinkmoth Nexus", color: "Land", manna_cost: "Land",types: "Land", rarity: "Rare", set: "Darksteel", value:33, quantity:1)
user1.magic_cards.create(name: "Blinkmouth nexus", color: "Land", manna_cost: "Land",types: "Land", rarity: "Rare", set: "Modern Masters", value:18, quantity:1)
user1.magic_cards.create(name: "Blistering Firecat", color: "Red", manna_cost: "1RRR",types: "Creature", rarity: "Rare", set: "Onslaught", value:1, quantity:2)
user1.magic_cards.create(name: "Blizzard Elemental", color: "Blue", manna_cost: "5UU",types: "Creature", rarity: "Rare", set: "Beatdown Box Set", value:1, quantity:1)
user1.magic_cards.create(name: "Blood Artist", color: "Land", manna_cost: "1B",types: "Creature ", rarity: "Uncommon", set: "Avacyn Restored", value:5, quantity:1)
user1.magic_cards.create(name: "Blood Artist", color: "Black", manna_cost: "1B",types: "Creature", rarity: "Uncommon", set: "Eternal Masters", value:3, quantity:3)
user1.magic_cards.create(name: "Blood baron of Vizkopa", color: "Multicolor", manna_cost: "3WB",types: "Creature", rarity: "Mythic Rare", set: "Dragon's Maze", value:10, quantity:1)
user1.magic_cards.create(name: "Blood Crypt", color: "Land", manna_cost: "Land",types: "Land", rarity: "Rare", set: "Return To Ravnica", value:15, quantity:4)
user1.magic_cards.create(name: "Blood moon", color: "Red", manna_cost: "2R",types: "Enchantment", rarity: "Rare", set: "Modern Masters", value:100, quantity:4)
user1.magic_cards.create(name: "Blood Moon ", color: "Red", manna_cost: "2R",types: "Enchantment", rarity: "Rare", set: "Eighth Edition", value:56, quantity:1)
user1.magic_cards.create(name: "Blood Moon ", color: "Red", manna_cost: "2R",types: "Enchantment", rarity: "Rare", set: "The Dark", value:50, quantity:4)
user1.magic_cards.create(name: "Blood Oath", color: "Red", manna_cost: "3R",types: "Instant", rarity: "Rare", set: "Mercadian Masques", value:2, quantity:1)
user1.magic_cards.create(name: "Blood Scrivener", color: "Black", manna_cost: "1B",types: "Creature", rarity: "Rare", set: "Dragon's Maze", value:1, quantity:1)
user1.magic_cards.create(name: "Blood Sun", color: "Red", manna_cost: "2R",types: "Enchantment", rarity: "Rare", set: "Rivals of Ixalan", value:4, quantity:2)
user1.magic_cards.create(name: "Blood Tribute", color: "Black", manna_cost: "4BB",types: "Sorcery", rarity: "Rare", set: "Zendikar", value:2, quantity:3)
user1.magic_cards.create(name: "Blood-Chin Fanatic", color: "Black", manna_cost: "1BB",types: "Creature", rarity: "Rare", set: "Dragons of Tarkir", value:2, quantity:1)
user1.magic_cards.create(name: "Bloodbraid Elf", color: "Multicolor", manna_cost: "2RG",types: "Creature", rarity: "Uncommon", set: "Shards of Alara", value:10, quantity:5)
user1.magic_cards.create(name: "Bloodbraid Elf", color: "Multicolor", manna_cost: "2RG",types: "Creature", rarity: "Uncommon", set: "Planeschase 2012", value:4, quantity:1)
user1.magic_cards.create(name: "Bloodchief Ascension", color: "Black", manna_cost: "B",types: "Enchantment", rarity: "Rare", set: "Zendikar", value:9, quantity:3)
user1.magic_cards.create(name: "Bloodgift Demon", color: "Black", manna_cost: "3BB",types: "Creature", rarity: "Rare", set: "Innistrad", value:2, quantity:1)
user1.magic_cards.create(name: "Bloodhall Priest", color: "Multicolor", manna_cost: "2BR",types: "Creature", rarity: "Rare", set: "Eldritch Moon", value:3, quantity:1)
user1.magic_cards.create(name: "Bloodline Keeper", color: "Black", manna_cost: "2BB",types: "Creature", rarity: "Rare", set: "Innistrad", value:10, quantity:2)
user1.magic_cards.create(name: "Bloodshot Cyclops", color: "Red", manna_cost: "5R",types: "Creature", rarity: "Rare", set: "Eighth Edition", value:1, quantity:1)
user1.magic_cards.create(name: "Bloodshot Cyclops", color: "Red", manna_cost: "5R",types: "Creature", rarity: "Rare", set: "Seventh Edition", value:1, quantity:1)
user1.magic_cards.create(name: "Bloodsoaked Champion", color: "Black ", manna_cost: "B",types: "Creature", rarity: "Rare", set: "Khans of Tarkir", value:3, quantity:2)
user1.magic_cards.create(name: "Bloodstained Mire", color: "Land ", manna_cost: "Land ",types: "Land ", rarity: "Rare", set: "Khans of Tarkir", value:37, quantity:12)
user1.magic_cards.create(name: "Bloodstained Mire", color: "Land", manna_cost: "Land",types: "Land", rarity: "Rare", set: "Onslaught", value:20, quantity:5)
user1.magic_cards.create(name: "Bloom Tender", color: "Green", manna_cost: "1G",types: "Creature", rarity: "Rare", set: "Eventide", value:25, quantity:4)
user1.magic_cards.create(name: "Blooming Marsh", color: "Land", manna_cost: "Land",types: "Land", rarity: "Rare", set: "Kaladesh", value:3, quantity:4)
user1.magic_cards.create(name: "Blue Elememental Blast", color: "Blue", manna_cost: "U",types: "Instant", rarity: "Common", set: "Alpha", value:12, quantity:1)
user1.magic_cards.create(name: "Blue Elememental Blast", color: "Blue", manna_cost: "U",types: "Instant", rarity: "Common", set: "Beta", value:10, quantity:3)
user1.magic_cards.create(name: "Blue Elememental Blast", color: "Blue", manna_cost: "U",types: "Instant", rarity: "Common", set: "Fourth Edition", value:1, quantity:2)
user1.magic_cards.create(name: "Blue Elemental Blast", color: "Blue", manna_cost: "U",types: "Instant", rarity: "Common", set: "Unlimited", value:8, quantity:4)
user1.magic_cards.create(name: "Blurred Mongoose", color: "Green", manna_cost: "1G",types: "Creature", rarity: "Rare", set: "Invasion", value:2, quantity:1)
user1.magic_cards.create(name: "Body Snatcher", color: "Black", manna_cost: "2BB",types: "Creature", rarity: "Rare", set: "Urza's Destiny", value:1, quantity:1)
user1.magic_cards.create(name: "Bogardan Hellkite", color: "Red", manna_cost: "6RR",types: "Creature", rarity: "Mythic Rare", set: "Magic 2010", value:3, quantity:1)
user1.magic_cards.create(name: "Bogbrew Witch", color: "Black", manna_cost: "3B",types: "Creature", rarity: "Rare", set: "Magic 2014", value:1, quantity:1)
user1.magic_cards.create(name: "Boggart Shenanigans", color: "Red", manna_cost: "2R",types: "Tribal Enchantment", rarity: "Rare", set: "Lorwyn", value:1, quantity:1)
user1.magic_cards.create(name: "Boil", color: "", manna_cost: "",types: "", rarity: "Uncommon", set: "Eight Edition", value:1, quantity:1)
user1.magic_cards.create(name: "Boil", color: "Red", manna_cost: "3R",types: "Instant", rarity: "Uncommon", set: "Sixth Edition", value:3, quantity:1)
user1.magic_cards.create(name: "Boil", color: "Red", manna_cost: "3R",types: "Instant", rarity: "Uncommon", set: "Tempest", value:4, quantity:2)
user1.magic_cards.create(name: "Bojuka Bog", color: "Land", manna_cost: "Land",types: "Land", rarity: "Common", set: "Worldwake", value:3, quantity:5)
user1.magic_cards.create(name: "Boltwing Marauder", color: "Multicolor", manna_cost: "3RB",types: "Creature", rarity: "Rare", set: "Dragons of Tarkir", value:2, quantity:1)
user1.magic_cards.create(name: "Bomat Courier", color: "Colorless", manna_cost: "1",types: "Artifact Creature", rarity: "Rare", set: "Aether Revolt", value:3, quantity:1)
user1.magic_cards.create(name: "Bomat Courier (Foil)", color: "Colorless", manna_cost: "1",types: "Artifact Creature", rarity: "Rare", set: "Kaladesh", value:3, quantity:1)
user1.magic_cards.create(name: "Bonescythe Sliver", color: "White", manna_cost: "3W",types: "Creature", rarity: "Rare", set: "Magic 2014", value:3, quantity:1)
user1.magic_cards.create(name: "Bonfire of the Damned", color: "Red", manna_cost: "XXR",types: "Sorcery", rarity: "Mythic Rare", set: "Avacyn Restored", value:20, quantity:3)
user1.magic_cards.create(name: "Bontu's Last Reckoning", color: "Black", manna_cost: "1BB",types: "Sorcery", rarity: "Rare", set: "Hour of Devastation", value:2, quantity:2)
user1.magic_cards.create(name: "Boomerang", color: "Blue", manna_cost: "UU",types: "Instant", rarity: "Common", set: "Legends", value:2, quantity:3)
user1.magic_cards.create(name: "Boon Reflection", color: "White", manna_cost: "4W",types: "Enchantment", rarity: "Rare", set: "Shadowmoor", value:8, quantity:1)
user1.magic_cards.create(name: "Boon Satyr", color: "Green", manna_cost: "1GG",types: "Enchantment Creature", rarity: "Rare", set: "Theros", value:2, quantity:2)
