# user1 = User.create(name: "sillhouette", password: "m")
# user2 = User.create(name: "iamcatdad", password: "catz4lyf3")
#
# user2.user_cards.build(magic_card_id: MagicCard.find(1).id, quantity: 5, quality: "mint", value: "$45")
# user1.user_cards.create(magic_card_id: MagicCard.find(2).id, quantity: 5, quality: "mint", value: "$45")
# user1.user_cards.create(magic_card_id: MagicCard.find(3).id, quantity: 5, quality: "mint", value: "$45")
# user1.user_cards.create(magic_card_id: MagicCard.find(4).id, quantity: 5, quality: "mint", value: "$45")
# user1.user_cards.create(magic_card_id: MagicCard.find(5).id, quantity: 5, quality: "mint", value: "$45")
# user1.user_cards.create(magic_card_id: MagicCard.find(6).id, quantity: 5, quality: "mint", value: "$45")
# user1.user_cards.create(magic_card_id: MagicCard.find(7).id, quantity: 5, quality: "mint", value: "$45")
# user1.user_cards.create(magic_card_id: MagicCard.find(8).id, quantity: 5, quality: "mint", value: "$45")
# user1.user_cards.create(magic_card_id: MagicCard.find(9).id, quantity: 5, quality: "mint", value: "$45")
# user1.user_cards.create(magic_card_id: MagicCard.find(10).id, quantity: 10, quality: "lightly played", value: "$400")
# user1.user_cards.create(magic_card_id: MagicCard.find(11).id, quantity: 10, quality: "lightly played", value: "$400")
# user1.user_cards.create(magic_card_id: MagicCard.find(12).id, quantity: 10, quality: "lightly played", value: "$400")
# user1.user_cards.create(magic_card_id: MagicCard.find(13).id, quantity: 10, quality: "lightly played", value: "$400")
# user1.user_cards.create(magic_card_id: MagicCard.find(14).id, quantity: 10, quality: "lightly played", value: "$400")
# user1.user_cards.create(magic_card_id: MagicCard.find(15).id, quantity: 10, quality: "lightly played", value: "$400")
# user1.user_cards.create(magic_card_id: MagicCard.find(16).id, quantity: 10, quality: "lightly played", value: "$400")
# user1.user_cards.create(magic_card_id: MagicCard.find(17).id, quantity: 10, quality: "lightly played", value: "$400")
# user1.user_cards.create(magic_card_id: MagicCard.find(18).id, quantity: 10, quality: "lightly played", value: "$400")
# user1.user_cards.create(magic_card_id: MagicCard.find(19).id, quantity: 10, quality: "lightly played", value: "$400")
# user1.user_cards.create(magic_card_id: MagicCard.find(20).id, quantity: 10, quality: "lightly played", value: "$400")
# user1.user_cards.create(magic_card_id: MagicCard.find(21).id, quantity: 10, quality: "lightly played", value: "$400")
# user1.user_cards.create(magic_card_id: MagicCard.find(22).id, quantity: 10, quality: "lightly played", value: "$400")
# user1.user_cards.create(magic_card_id: MagicCard.find(23).id, quantity: 10, quality: "lightly played", value: "$400")
# user1.user_cards.create(magic_card_id: MagicCard.find(24).id, quantity: 10, quality: "lightly played", value: "$400")
# user1.user_cards.create(magic_card_id: MagicCard.find(25).id, quantity: 10, quality: "lightly played", value: "$400")
